namespace DefaultNamespace
{
    public enum PropertyKey
    {
        NONE,
        HEALTH,
        MAX_HEALTH,
        ACTION_POINTS,
        POWER,
        MAX_POWER,
        HAND_SIZE,
        TURN_COUNTDOWN,
        MAX_TURN_COUNTDOWN,
        ATTACK,
        SHIELD,
        POWER_UP,
        CARDS_DISCARDED_ON_CURRENT_TURN_COUNT,
        CARDS_DISCARDED_ON_CURRENT_BATTLE_COUNT,
        CARDS_DESTROYED_ON_CURRENT_TURN_COUNT,
        CARDS_DESTROYED_ON_CURRENT_BATTLE_COUNT,
        CARDS_FADED_ON_CURRENT_TURN_COUNT,
        CARDS_FADED_ON_CURRENT_BATTLE_COUNT,
        CANNOT_DRAW_ADDITIONAL_CARDS_CURRENT_TURN,
    }
}